### ISSUE TITLE
Divide by Zero Issue bei Interpolationssuche

### ISSUE THREAD

**Issue by JSiggelkow** [NErzberger/Vorlesung-Programmierung-2#4]
Es existiert ein Fehler bei der Implementierung der Interpolationssuche:

Bei der Berechnung des Pivot-Elements:

`pivotPos = linkeGrenze + (searchValue - searchBase[linkeGrenze]) /
                    (searchBase[rechteGrenze] - searchBase[linkeGrenze]) *
                    (rechteGrenze - linkeGrenze);`

besteht die Chance, dass "(searchBase[rechteGrenze] - searchBase[linkeGrenze])" 0 ergibt.
In diesem Fall wird eine "/ by Zero" ArithmeticException ausgelöst.

Wenn z.B. das zu durchsuchende Array = {9,9,9} ist würde ein solcher Fehler auftreten und ein solches Array ist ein sortiertes Array und somit für die Interpolationssuche zulässig.

**Comment by NErzberger** [comment]
Stimmt, diesen Fall hatte ich nicht auf dem Schirm.

Danke für den Hinweis!
