### ISSUE TITLE
Fehler in Implementierungen - Klausur

### ISSUE THREAD

**Issue by JSiggelkow** [NErzberger/Vorlesung-Programmierung-2#5]
Sehr geehrter Herr Erzberger,
da sich nun schon in mehreren Ihrer Implementierungen kleine Fehler (z.B. SelectionSort, LinkedList, InterpolationSearch eingeschlichen haben, stellt sich mir die Frage wie dieses Problem in der Klausur gehandhabt wird?

Dürfen wir in der Klausur den richtigen Code schreiben, oder sollen wir die fehlerbehafteten Implementierungen benutzen?
Oder ist es egal, da die Fehler erst nach der letzten Vorlesung aufgefallen sind?

Ich freue mich auf eine Rückmeldung.
Vielen Dank und ein schönes Wochenende

**Comment by NErzberger** [comment]
Hallo,

in der Klausur sind immer beide Varianten, die korrigierte oder die aus dem Skript in Ordnung und werden voll bepunktet.

Viel Erfolg weiterhin,

Nico Erzberger

**Comment by JSiggelkow** [comment]
Danke!
