### ISSUE TITLE
NullPointerException in LinkedList delete(Object o) methode und Verbesserung LinkedList

### ISSUE THREAD

**Issue by JSiggelkow** [NErzberger/Vorlesung-Programmierung-2#6]
Sehr geehrter Herr Erzberger,
wenn auf einer leeren Liste die Methode remove(Object o) aufgerufen wird, entsteht eine NullPointerException, weil first null ist und darauf dann Methoden aufgerufen werden.

Generell könnte man auch überlegen sich bei der Implementierung der Node-Klasse mehr an der offiziellen Implementierung zu orientierten.
Offizielle Implementierung:
`private static class Node<E> {
        E item;
        Node<E> next;
        Node<E> prev;

        Node(Node<E> prev, E element, Node<E> next) {
            this.item = element;
            this.next = next;
            this.prev = prev;
        }
    }`

Dies ist zwar kein Fix für dieses Issue,  würde aber die gesamte LinkedList lesbarer und verständlicher machen.
Man würde sich die vielen verschiedenen Setter und Getter Methoden sparen und neue Nodes direkt über den Constructor erstellen bzw. verknüpfen können.

Diese Änderung könnte z.B. die Add-Methode extrem verkürzen bzw. verbessern:

`public boolean add(E e) {

        Node l = last;
        last = new Node(l, e, null);
        if (l == null) {
            first = last;
        } else {
            l.next = last;
        }
        size++;
        return true;
    }`

Den passenden Fix zur NullPointerException könnte ich als PR bereitstellen, jedoch würde ich gerne erst Ihre Meinung zu der Verbesserung der LinkedList / Node hören, denn gegebenenfalls könnte man mit einem kompletten Refactoring der LinkedList die Fehler beheben.

Freundliche Grüße und ein schönes Wochenende

**Comment by NErzberger** [comment]
Hallo,
Diesen Fall hatte ich einfach nicht vorgesehen, da es selten vorkommt.

Um dies abzufangen muss vorher de Frist Variable geprüfte werden und wenn sie null ist mit einer exception verlassen werden.
Streng genommen wäre die nullpointerexception sogar richtig.

Die delete Methode auf eine leere Liste auszuführen ist generell nicht sehr empfehlenswert.

Du kannst natürlich für dich den Konstruktor anpassen und in der Klausur direkt alle Parameter der node mitgeben. Das wurde auch in der Vorlesung besprochen. Zweck dem Verständnis was alles benötigt wird und dass es übersichtlicher ist hatte ich die Parameter einzeln gesetzt.

Weiterhin viel erfolg, 

Nico Erzberger

**Comment by NErzberger** [comment]
Ich habe gerade einen bugfix gepusht.

**Comment by JSiggelkow** [comment]
Okay, viele Dank!
